#!/bin/bash

# attribution
#   Written using this great (but slightly outdated) guide:
#   https://czak.pl/2015/09/15/s3-rest-api-with-curl.html

# functions
function get_hmac_sha256 {
  if [ $# -le 1 ]; then
    echo "error: get_hmac_sha256 needs args" 
    echo "usage:"
    echo "  get_hmac_sha256 key:<key> <data>"
    exit 1
  fi

  key="$1"
  data="$2"

  echo -n "$data" |  openssl dgst -sha256 -mac HMAC -macopt "$key" | awk '{print $2}'
}

function parse_role_info {
  if [ $# -ne 1 ]; then
    echo "error: need a parm to parse"
    exit 1
  fi

  iam_key="$1"
  grep "$iam_key" role_info | awk -F '"' '{print $4}'
}

# s3 account info
bucket="csm-dev-a"
endpoint="https://s3.us-east-2.amazonaws.com"
instance_metadata="http://169.254.169.254/latest/meta-data/iam/security-credentials/"
iam_role="csm-dev"
region="us-east-2"
service="s3"

curl $instance_metadata/$iam_role > role_info

cat role_info

access_key=$(parse_role_info "AccessKeyId")
secret_key=$(parse_role_info "SecretAccessKey")
token=$(parse_role_info "Token")

# date, timestamp, hashes, etc.
date_ymd=`date +%Y%m%d`
ts=`date -u +%Y%m%d'T'%H%M%S'Z'`
empty_hash=`openssl dgst -sha256 /dev/null | awk '{print $2}'`
http_req="HEAD"

# build canonical request
cr_str="$http_req
/$bucket

host:s3.us-east-2.amazonaws.com
x-amz-content-sha256:$empty_hash
x-amz-date:$ts
x-amz-security-token:$token

host;x-amz-content-sha256;x-amz-date;x-amz-security-token
$empty_hash"

cr_hash=`echo -n "$cr_str" | openssl dgst -sha256 | awk '{print $2}'`

# build string to sign
sts="AWS4-HMAC-SHA256
$ts
$date_ymd/$region/$service/aws4_request
$cr_hash"

# signing key from date keys
d_key=$(get_hmac_sha256 key:"AWS4$secret_key" $date_ymd)
dr_key=$(get_hmac_sha256 hexkey:$d_key $region)
drs_key=$(get_hmac_sha256 hexkey:$dr_key $service)
signing_key=$(get_hmac_sha256 hexkey:$drs_key "aws4_request")
req_signature=$(get_hmac_sha256 hexkey:$signing_key "$sts")

auth_hdr="Authorization: AWS4-HMAC-SHA256 Credential=$access_key/$date_ymd/$region/s3/aws4_request, \
          SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, \
          Signature=$req_signature" 

curl \
  -I \
  -H "$auth_hdr" \
  -H "x-amz-content-sha256: $empty_hash" \
  -H "x-amz-date: $ts" \
  -H "x-amz-security-token: $token" \
  -H "Content-Length: 0" \
  "https://s3.us-east-2.amazonaws.com/$bucket"
